### ISSUE TITLE
Web Scraping the html for the tables 

### ISSUE THREAD

**Issue by timbo112711** [New-Jersey-Forest-Service/FIAPI#2]
The issue I am having with the web scraping of the html is going through the html code and pulling out the info that the 'tr' and 'td' parts hold. These parts have the info that is attached to each table. When looking at the WebScrapingTest.py file, the code runs up to line 23. After line 23 is where we need to pull the info from the html and store it in either a data frame or csv file.

**Comment by wzip** [comment]
I am closing this issue, since updates to EVALIDator allow requests for data files other than just HTML tables.  Scraping is not really necessary now that users can request data in different formats.
